from typing import List, Dict, Any, Optional
from datetime import datetime, timedelta
from sqlalchemy.orm import Session, joinedload
from sqlalchemy import func, case
from app.models.domain import (
    User, LearnerProfile, LearnerAlphabetState, AssessmentAttempt,
    PracticeSession, Certification, Feedback, StateEnum
)
from app.services.learner_state_service import evaluate_and_update_state

ALL_SIGNS = [
    'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
    'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
    'DEL', 'NOTHING', 'SPACE'
]

class PracticeAnalyticsService:
    """
    Single Authoritative Source of Truth for Practice Attempts,
    Mastery Categorization, Session Performance Trends, and Dashboard Analytics.
    """

    @staticmethod
    def calculate_practice_streak(db: Session, user_id: int) -> int:
        """Calculates consecutive practice days from actual attempt timestamps."""
        attempts = db.query(AssessmentAttempt.timestamp).filter(
            AssessmentAttempt.learner_id == user_id
        ).order_by(AssessmentAttempt.timestamp.desc()).limit(200).all()
        
        if not attempts:
            return 0
            
        dates = sorted({a.timestamp.date() for a in attempts if a.timestamp}, reverse=True)
        if not dates:
            return 0
            
        today = datetime.utcnow().date()
        yesterday = today - timedelta(days=1)
        
        # If user did not practice today or yesterday, streak is 0
        if dates[0] != today and dates[0] != yesterday:
            return 0
            
        streak = 1
        current_check = dates[0]
        
        for next_date in dates[1:]:
            if next_date == current_check - timedelta(days=1):
                streak += 1
                current_check = next_date
            elif next_date == current_check:
                continue
            else:
                break
                
        return streak

    @staticmethod
    def record_attempt(
        db: Session,
        learner: User,
        expected_sign: str,
        predicted_sign: str,
        confidence: float,
        is_correct: Optional[bool] = None,
        gesture_accuracy: Optional[float] = None,
        feedback_text: Optional[str] = None,
        session_id: Optional[int] = None
    ) -> Dict[str, Any]:
        """
        Authoritatively persists a practice attempt result generated by the live ML evaluation.
        DOES NOT re-predict or alter model outputs.
        """
        clean_expected = (expected_sign or "A").strip().upper()
        clean_predicted = (predicted_sign or "A").strip().upper()
        
        # Canonical confidence range: 0.0 - 1.0
        conf_float = float(confidence) if confidence is not None else 0.0
        if conf_float > 1.0:
            conf_float = conf_float / 100.0
        conf_float = max(0.0, min(1.0, conf_float))

        # Determine correctness & accuracy
        is_corr = is_correct if is_correct is not None else (clean_expected == clean_predicted)
        acc_float = float(gesture_accuracy) if gesture_accuracy is not None else (100.0 if is_corr else 0.0)

        # Standardized feedback
        if not feedback_text:
            if is_corr:
                feedback_text = f"Correct! You performed sign {clean_expected}."
            else:
                feedback_text = f"Detected sign {clean_predicted}. Please perform sign {clean_expected}."

        correction = "Maintain finger extension." if is_corr else f"Adjust finger alignment and thumb placement for sign '{clean_expected}'."

        # 1. Create Feedback
        feedback_obj = Feedback(
            feedback_text=feedback_text,
            correction_suggestion=correction,
            error_category="Landmark Alignment" if not is_corr else "None"
        )
        db.add(feedback_obj)
        db.flush()

        # 2. Persist AssessmentAttempt (Single Source of Truth)
        attempt = AssessmentAttempt(
            session_id=session_id,
            learner_id=learner.id,
            expected_sign=clean_expected,
            predicted_sign=clean_predicted,
            is_correct=is_corr,
            confidence=conf_float,
            gesture_accuracy=acc_float,
            hand_shape_accuracy=100.0 if is_corr else 0.0,
            position_accuracy=100.0 if is_corr else 0.0,
            motion_accuracy=100.0 if is_corr else 0.0,
            timing_score=95.0,
            stability_score=90.0,
            invalid_frame_count=0,
            inference_time=12.0,
            timestamp=datetime.utcnow(),
            feedback_id=feedback_obj.id
        )
        db.add(attempt)
        db.flush()

        # 3. Update PracticeSession if session_id provided
        if session_id:
            sess = db.query(PracticeSession).filter(
                PracticeSession.id == session_id,
                PracticeSession.learner_id == learner.id
            ).first()
            if sess:
                sess.total_attempts = (sess.total_attempts or 0) + 1
                if is_corr:
                    sess.correct_count = (sess.correct_count or 0) + 1
                else:
                    sess.incorrect_count = (sess.incorrect_count or 0) + 1
                
                n = sess.total_attempts
                sess.average_accuracy = round(((sess.correct_count or 0) / n) * 100.0, 1)
                curr_sess_conf = sess.average_confidence or 0.0
                sess.average_confidence = round(((curr_sess_conf * (n - 1)) + (conf_float * 100.0)) / n, 1)

        # 4. Update LearnerAlphabetState
        st = db.query(LearnerAlphabetState).filter(
            LearnerAlphabetState.learner_id == learner.id,
            LearnerAlphabetState.sign_character == clean_expected
        ).first()

        if not st:
            st = LearnerAlphabetState(
                learner_id=learner.id,
                sign_character=clean_expected,
                current_state=StateEnum.NOT_ATTEMPTED,
                total_attempts=0,
                successful_attempts=0,
                consecutive_correct=0,
                consecutive_incorrect=0,
                average_accuracy=0.0,
                average_confidence=0.0,
                mastery_percentage=0.0
            )
            db.add(st)
            db.flush()

        st.total_attempts = (st.total_attempts or 0) + 1
        if is_corr:
            st.successful_attempts = (st.successful_attempts or 0) + 1
        
        st.average_accuracy = round(((st.successful_attempts or 0) / st.total_attempts) * 100.0, 1)
        prev_conf = st.average_confidence or 0.0
        st.average_confidence = round(((prev_conf * (st.total_attempts - 1)) + (conf_float * 100.0)) / st.total_attempts, 1)
        st.mastery_percentage = st.average_accuracy

        # Evaluate authoritative state transition
        evaluate_and_update_state(
            db=db,
            state_obj=st,
            latest_accuracy=acc_float,
            is_correct=is_corr,
            latest_confidence=conf_float * 100.0
        )

        # 5. Update LearnerProfile
        profile = db.query(LearnerProfile).filter(LearnerProfile.user_id == learner.id).first()
        if not profile:
            profile = LearnerProfile(user_id=learner.id)
            db.add(profile)
            db.flush()

        # Recalculate profile overall performance and streak
        total_user_attempts = db.query(AssessmentAttempt).filter(AssessmentAttempt.learner_id == learner.id).count()
        total_user_correct = db.query(AssessmentAttempt).filter(
            AssessmentAttempt.learner_id == learner.id,
            AssessmentAttempt.is_correct == True
        ).count()

        profile.overall_performance_score = round((total_user_correct / total_user_attempts) * 100.0, 1) if total_user_attempts > 0 else 0.0
        profile.practice_streak_days = PracticeAnalyticsService.calculate_practice_streak(db, learner.id)
        profile.last_practice_at = datetime.utcnow()
        
        db.commit()
        db.refresh(attempt)

        # 6. Event-Driven Achievement Unlock Check
        from app.services.achievement_service import AchievementService
        unlocked_ach = AchievementService.check_and_unlock_for_attempt(db, learner.id, clean_expected)

        return {
            "id": attempt.id,
            "expected_sign": clean_expected,
            "predicted_sign": clean_predicted,
            "confidence": conf_float,
            "confidence_percentage": round(conf_float * 100.0, 1),
            "is_correct": is_corr,
            "accuracy": acc_float,
            "feedback": feedback_text,
            "created_at": attempt.timestamp.isoformat(),
            "unlocked_achievement": unlocked_ach
        }

    @staticmethod
    def get_dashboard_summary(db: Session, current_user: User) -> Dict[str, Any]:
        """
        Retrieves authoritative, 100% data-driven dashboard analytics for current_user.
        Optimized with single-pass batch SQL aggregations and composite index usage.
        """
        profile = db.query(LearnerProfile).filter(LearnerProfile.user_id == current_user.id).first()
        if not profile:
            profile = LearnerProfile(user_id=current_user.id)
            db.add(profile)
            db.commit()
            db.refresh(profile)

        # 1. Single-Pass Grouped SQL Query for All Signs Statistics
        sign_stats_rows = db.query(
            AssessmentAttempt.expected_sign,
            func.count(AssessmentAttempt.id).label("total_attempts"),
            func.sum(case((AssessmentAttempt.is_correct == True, 1), else_=0)).label("correct_attempts"),
            func.avg(case((AssessmentAttempt.confidence <= 1.0, AssessmentAttempt.confidence * 100.0), else_=AssessmentAttempt.confidence)).label("avg_conf"),
            func.max(AssessmentAttempt.timestamp).label("last_time")
        ).filter(
            AssessmentAttempt.learner_id == current_user.id
        ).group_by(
            AssessmentAttempt.expected_sign
        ).all()

        total_attempts_count = sum(int(r.total_attempts) for r in sign_stats_rows) if sign_stats_rows else 0
        correct_attempts_count = sum(int(r.correct_attempts or 0) for r in sign_stats_rows) if sign_stats_rows else 0

        # 2. Overall Accuracy & Score: (correct / total) * 100
        if total_attempts_count > 0:
            overall_score = round((correct_attempts_count / total_attempts_count) * 100.0, 1)
            overall_accuracy = overall_score
            conf_weighted_sum = sum((float(r.avg_conf) if r.avg_conf is not None else 0.0) * int(r.total_attempts) for r in sign_stats_rows)
            avg_confidence = round(conf_weighted_sum / total_attempts_count, 1)
        else:
            overall_score = None
            overall_accuracy = None
            avg_confidence = None

        # 3. Practice Sessions & Chronological Trend
        user_sessions_db = db.query(PracticeSession).filter(
            PracticeSession.learner_id == current_user.id
        ).order_by(PracticeSession.start_time.asc()).all()

        total_sessions_count = len(user_sessions_db)
        latest_session = user_sessions_db[-1] if user_sessions_db else None

        if latest_session and latest_session.total_attempts > 0:
            latest_session_accuracy = round(float(latest_session.average_accuracy), 1)
        else:
            latest_session_accuracy = None

        # 4. Practice Streak from actual dates (with index and limit)
        streak_days = PracticeAnalyticsService.calculate_practice_streak(db, current_user.id)

        # 5. Build 29-Class Sign Statistics & Authoritative Classification in Memory
        stats_map = {(r.expected_sign or "").strip().upper(): r for r in sign_stats_rows}

        sign_classification = []
        mastered_chars = []
        learning_chars = []
        practicing_chars = []
        revision_chars = []

        for sign_char in ALL_SIGNS:
            row = stats_map.get(sign_char)
            sign_total = int(row.total_attempts) if row else 0
            sign_correct = int(row.correct_attempts) if (row and row.correct_attempts is not None) else 0
            sign_acc = round((sign_correct / sign_total) * 100.0, 1) if sign_total > 0 else 0.0
            sign_avg_conf = round(float(row.avg_conf), 1) if (row and row.avg_conf is not None) else 0.0
            last_time = row.last_time.isoformat() if (row and row.last_time) else None

            # Authoritative Mastery Classification Rules
            if sign_total == 0:
                category = "Not Attempted"
                state_enum = StateEnum.NOT_ATTEMPTED
            elif sign_total >= 5 and sign_acc >= 85.0 and sign_avg_conf >= 85.0:
                category = "Mastered"
                state_enum = StateEnum.MASTERED
                mastered_chars.append(sign_char)
            elif sign_total >= 2 and sign_acc >= 50.0:
                category = "Practicing"
                state_enum = StateEnum.IMPROVING
                practicing_chars.append(sign_char)
            elif sign_total >= 3 and sign_acc < 50.0:
                category = "Needs Revision"
                state_enum = StateEnum.NEEDS_REVISION
                revision_chars.append(sign_char)
            else:
                category = "Learning"
                state_enum = StateEnum.LEARNING
                learning_chars.append(sign_char)

            sign_classification.append({
                "sign": sign_char,
                "character": sign_char,
                "total_attempts": sign_total,
                "correct_attempts": sign_correct,
                "accuracy": sign_acc,
                "average_confidence": sign_avg_conf,
                "category": category,
                "state": state_enum.value,
                "last_practiced_at": last_time
            })

        # Strongest (strictly Mastered signs), Weakest & Revision Lists
        strongest_signs = [s["sign"] for s in sign_classification if s["category"] == "Mastered"]
        weakest_signs = [
            s["sign"] for s in sign_classification 
            if s["total_attempts"] > 0 and s["category"] != "Mastered" and s["accuracy"] < 60.0
        ]
        signs_needing_revision = [s["sign"] for s in sign_classification if s["category"] == "Needs Revision"]

        core_alphabet_mastered = len([s for s in sign_classification if s["sign"] in ALL_SIGNS[:26] and s["category"] == "Mastered"])
        lesson_completion_rate = round((core_alphabet_mastered / 26.0) * 100.0, 1)

        # Attempted signs only for compact mastery_list
        attempted_mastery_list = [s for s in sign_classification if s["total_attempts"] > 0]

        # 6. Adaptive Recommendation
        if total_attempts_count == 0:
            recommended_sign = "A"
            recommendation_reason = "Welcome to ASL Sensei! Start practicing foundational sign 'A' with your webcam."
        elif weakest_signs:
            recommended_sign = weakest_signs[0]
            rec_stat = next((s for s in sign_classification if s["sign"] == recommended_sign), None)
            rec_acc = f"{rec_stat['accuracy']:.1f}%" if rec_stat else "low"
            recommendation_reason = f"Sign '{recommended_sign}' has an accuracy of {rec_acc}. Targeted practice will resolve confusion!"
        elif core_alphabet_mastered < 26:
            unmastered = [s["sign"] for s in sign_classification if s["sign"] in ALL_SIGNS[:26] and s["category"] != "Mastered"]
            recommended_sign = unmastered[0] if unmastered else "A"
            recommendation_reason = f"Advance your vocabulary by practicing sign '{recommended_sign}'."
        else:
            recommended_sign = "A"
            recommendation_reason = "Congratulations! You have mastered all signs. Practice sign 'A' to maintain your skills."

        # 7. Session Performance Trend (Single Batch Query for All Sessions)
        session_stats_rows = db.query(
            AssessmentAttempt.session_id,
            func.count(AssessmentAttempt.id).label("total_attempts"),
            func.sum(case((AssessmentAttempt.is_correct == True, 1), else_=0)).label("correct_attempts")
        ).filter(
            AssessmentAttempt.learner_id == current_user.id,
            AssessmentAttempt.session_id.isnot(None)
        ).group_by(
            AssessmentAttempt.session_id
        ).all()
        session_stats_map = {r.session_id: r for r in session_stats_rows}

        session_trend = []
        valid_session_idx = 1
        for s in user_sessions_db:
            s_stat = session_stats_map.get(s.id)
            att_count = int(s_stat.total_attempts) if s_stat else s.total_attempts
            corr_count = int(s_stat.correct_attempts) if (s_stat and s_stat.correct_attempts is not None) else s.correct_count

            if att_count > 0:
                s_acc = round((corr_count / att_count) * 100.0, 1)
                date_str = s.start_time.strftime("%b %d") if s.start_time else f"Session {valid_session_idx}"
                session_trend.append({
                    "session_id": s.id,
                    "session_number": valid_session_idx,
                    "label": f"Session {valid_session_idx}",
                    "date": s.start_time.isoformat() if s.start_time else None,
                    "date_formatted": date_str,
                    "attempts": att_count,
                    "correct_attempts": corr_count,
                    "accuracy": s_acc,
                    "score": s_acc
                })
                valid_session_idx += 1

        # 8. Recent Attempt History (Joined feedback in 1 single roundtrip)
        recent_attempts_db = db.query(AssessmentAttempt).options(
            joinedload(AssessmentAttempt.feedback_obj)
        ).filter(
            AssessmentAttempt.learner_id == current_user.id
        ).order_by(AssessmentAttempt.timestamp.desc()).limit(10).all()

        recent_attempts = []
        for a in recent_attempts_db:
            conf_percent = round(a.confidence * 100.0, 1) if a.confidence <= 1.0 else round(a.confidence, 1)
            attempt_acc = 100.0 if a.is_correct else 0.0
            fb_text = a.feedback_obj.feedback_text if a.feedback_obj else (
                f"Correct! You performed sign {a.expected_sign}." if a.is_correct else f"Detected sign {a.predicted_sign}. Please perform sign {a.expected_sign}."
            )
            recent_attempts.append({
                "id": a.id,
                "expected_sign": a.expected_sign,
                "predicted_sign": a.predicted_sign,
                "confidence": conf_percent,
                "overall_accuracy": attempt_acc,
                "is_correct": a.is_correct,
                "feedback": fb_text,
                "created_at": a.timestamp.isoformat() if a.timestamp else None
            })

        # 9. Certificates Count
        certificates_count = db.query(Certification).filter(Certification.user_id == current_user.id).count()

        # 10. Build Canonical Dictionary Mapping for Alphabet Mastery Matrix
        matrix_dict = {}
        for item in sign_classification:
            s_name = item["sign"]
            cat = item["category"]
            color = "green" if cat == "Mastered" else ("blue" if cat in ["Practicing", "Learning"] else ("red" if cat == "Needs Revision" else "gray"))
            matrix_dict[s_name] = {
                "status": cat,
                "color": color,
                "accuracy": item["accuracy"],
                "total_attempts": item["total_attempts"],
                "average_confidence": item["average_confidence"]
            }

        return {
            "user": {
                "id": current_user.id,
                "full_name": current_user.full_name,
                "email": current_user.email,
                "role": current_user.role.value,
                "learning_level": profile.learning_level.value if hasattr(profile.learning_level, "value") else str(profile.learning_level or "Beginner"),
                "preferred_language": profile.preferred_language or "English"
            },
            "profile": {
                "id": profile.id,
                "user_id": profile.user_id,
                "learning_level": profile.learning_level.value if hasattr(profile.learning_level, "value") else str(profile.learning_level or "Beginner"),
                "preferred_language": profile.preferred_language or "English",
                "overall_performance_score": profile.overall_performance_score or 0.0,
                "practice_streak_days": streak_days,
                "total_practice_time_mins": profile.total_practice_time_mins or 0,
                "total_sessions_count": total_sessions_count,
                "total_attempts_count": total_attempts_count,
                "average_confidence": avg_confidence,
                "last_practice_at": profile.last_practice_at.isoformat() if profile.last_practice_at else None
            },
            "performance": {
                "overall_score": overall_score,
                "overall_accuracy": overall_accuracy,
                "current_session_accuracy": latest_session_accuracy,
                "total_sessions": total_sessions_count,
                "total_attempts": total_attempts_count,
                "average_confidence": avg_confidence,
                "practice_streak_days": streak_days,
                "total_practice_time_mins": profile.total_practice_time_mins or 0
            },
            "lessons": {
                "completed": core_alphabet_mastered,
                "total": 26,
                "progress_percent": lesson_completion_rate
            },
            "certificates": {
                "earned": certificates_count
            },
            "sign_classification": sign_classification,
            "alphabet_mastery_matrix": matrix_dict,
            "mastery_list": attempted_mastery_list,
            "strongest_signs": strongest_signs,
            "weakest_signs": weakest_signs,
            "signs_needing_revision": signs_needing_revision,
            "mastery_counts": {
                "mastered": len(mastered_chars),
                "practicing": len(practicing_chars),
                "learning": len(learning_chars),
                "needs_revision": len(revision_chars),
                "not_attempted": 29 - (len(mastered_chars) + len(practicing_chars) + len(learning_chars) + len(revision_chars))
            },
            "recommended_sign": recommended_sign,
            "recommendation_reason": recommendation_reason,
            "session_trend": session_trend,
            "recent_attempts": recent_attempts,
            "has_data": total_attempts_count > 0
        }
